describe(`the isPalindrome function`, () => {
  test.todo(`returns "true" for a "level"`)
  test.todo(`returns "true" for a "radar"`)
  test.todo(`returns "true" for a "kayak"`)
  test.todo(`returns "true" for a "madam"`)
  test.todo(`returns "false" for a "lover"`)
  test.todo(`returns "false" for a "saint"`)
  test.todo(`returns "false" for a "heh heh"`)
  test.todo(`returns "true" for a "a"`)
  test.todo(`returns "true" for a "e"`)
  test.todo(`returns "false" for a 1`)
  test.todo(`returns "false" for a 0`)
  test.todo(`returns "false" for a 9`)
  test.todo(`returns "false" for a 1628`)
  test.todo(`returns "true" for a " "`)
  test.todo(`returns "true" for a "   "`)
  test.todo(`returns "true" for a ""`)
  test.todo(`throw for a []`)
  test.todo(`throw for a {}`)
  test.todo(`throw for a null`)
})
