describe('the isPalindrome function', () => {
  test.todo('returns true for "level"')
  test.todo('returns true for "radar"')
  test.todo('returns true for "kayak"')
  test.todo('returns true for "madam"')
  test.todo('returns false for "lover"')
  test.todo('returns false for "saint"')
  test.todo('returns false for "heh heh"')
  test.todo('returns false for "a"')
  test.todo('returns false for "e"')
  test.todo('returns false for "1"')
  test.todo('returns false for "0"')
  test.todo('returns false for "9"')
  test.todo('returns false for "1628"')
  test.todo('returns false for " "')
  test.todo('returns false for "   "')
  test.todo('returns false for ""')
  test.todo('throw for a []')
  test.todo('throw for a {}')
  test.todo('throw for a null')
})
